name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: arjunsaxaena
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          message: "generate contribution snake"
          add: "dist/"
